### ISSUE TITLE
Instalação Composer x Manual

### ISSUE THREAD

**Issue by mageuser** [thiagolima-bm/magento2doc#1]
Olá, parabéns pela iniciativa!
Estava lendo a wiki/instalação e eu estou usando o instalador do magento, tem alguma diferença além da velocidade de instalação?

**Comment by thiagolima-bm** [comment]
Olá, @kauansoft. Obrigado.
Se for só para instalar, não tem nenhuma diferença. Mas, eu prefiro utilizar o composer. Dentre outras vantagens, utilizando o instalador por exemplo, você nao consegue atualizar a versão do magento.
